# Generated by Django 6.0.2 on 2026-03-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10, verbose_name='Gender')),
                ('ability', models.CharField(max_length=100, verbose_name='Ability')),
                ('description', models.TextField(verbose_name='Description')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL images')),
                ('quote', models.CharField(blank=True, max_length=200, null=True, verbose_name='Quote')),
            ],
            options={
                'verbose_name': 'Character',
                'verbose_name_plural': 'Characters',
            },
        ),
        migrations.CreateModel(
            name='Empire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('credo', models.CharField(max_length=200, verbose_name='Credo')),
                ('anthem', models.TextField(verbose_name='Anthem')),
                ('description', models.TextField(verbose_name='Description')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL images')),
            ],
            options={
                'verbose_name': 'Empire',
                'verbose_name_plural': 'Empires',
            },
        ),
    ]
