# Generated by Django 6.0.2 on 2026-03-28 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='empire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.empire', verbose_name='Принадлежность к Империи'),
        ),
        migrations.AddField(
            model_name='character',
            name='has_will',
            field=models.BooleanField(default=False, verbose_name='Has Imperial Will'),
        ),
        migrations.AddField(
            model_name='character',
            name='is_ruler',
            field=models.BooleanField(default=False, verbose_name='Is Ruler'),
        ),
        migrations.AddField(
            model_name='empire',
            name='faction',
            field=models.CharField(choices=[('NOCTIS', 'Noctis'), ('LUMEN', 'Lumen'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='Faction'),
        ),
        migrations.AlterField(
            model_name='character',
            name='age',
            field=models.IntegerField(verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10, verbose_name='Gender'),
        ),
    ]
