# Generated by Django 6.0.2 on 2026-03-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_character_empire_character_has_will_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='character',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Weight'),
        ),
    ]
