# Generated by Django 6.0.2 on 2026-04-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_character_height_character_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок отображения'),
        ),
        migrations.AddField(
            model_name='empire',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок отображения'),
        ),
    ]
