# Generated by Django 6.0.2 on 2026-04-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_character_order_empire_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='empire',
            name='heir',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Heir'),
        ),
        migrations.AddField(
            model_name='empire',
            name='ruler',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Rulers'),
        ),
    ]
