# Generated by Django 6.0.2 on 2026-04-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_empire_heir_empire_ruler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empire',
            name='anthem',
            field=models.TextField(blank=True, null=True, verbose_name='Anthem'),
        ),
        migrations.AlterField(
            model_name='empire',
            name='heir',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Heir'),
        ),
    ]
