# Generated by Django 6.0.2 on 2026-04-02 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_empire_anthem_alter_empire_heir'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ancestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Image URL')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('quote', models.CharField(blank=True, max_length=200, null=True, verbose_name='Quote')),
                ('lifespan', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lifespan')),
                ('order', models.IntegerField(default=0, verbose_name='Display order')),
                ('empire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.empire', verbose_name='Empire')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='main.ancestor', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Ancestor',
                'verbose_name_plural': 'Ancestors',
                'ordering': ['order', 'lifespan'],
            },
        ),
    ]
